### ISSUE TITLE
Upload hangs for Dropbox

### ISSUE THREAD

**Issue by roseregina** [OpenArchive/Save-app-ios#177] opened 2020-04-13 19:47 UTC
Save 2.6.0 (50), installed through Testflight
Dropbox server (my personal account)
iPhone 11

Expected Behaviour: 
1. Add images to upload
2. Click on the circled number in the upper right to see queue
3. Files are uploading to Dropbox 
4. Files finish uploading and queue is empty 

Actual Behaviour: 
1. Add images to upload
2. Click on the circled number in the upper right to see queue
3. First file is uploading to Dropbox 
4. First file appears as though all of the data has been uploaded, but file is not displayed as complete, upload of next file is not starting
![image](https://user-images.githubusercontent.com/15040203/79153706-e4c4f900-7d93-11ea-869b-7e6c15058e94.png)
even through both image and json are on dropbox (see note below) 
5. Pause upload by clicking "Edit" in the upper right
6. Unpause upload by clicking "Done" in the upper right
7. Upload progress wheel displays action again briefly, then file registers as fully uploaded and disappears from the queue
8. At this point, either there are no more images in the queue, or it stalls again like in **step 4** and I have to repeat **steps 5 & 6** for each image. 

**NOTE:** I observed this both with single image uploads and batch image uploads. Adding more images to the queue **did not** do anything to change the need to manually interact for each image. 

Interestingly, there seems to be some kind of discrepancy in that I was able to access the uploaded file on the server before the the upload registered as complete in the app on my phone. Does more information on this seem relevant? I opened the Dropbox web interface and observed the files appearing and checked that the image and matching json were complete enough to open and look correct. My hunch is that confirmation of file upload from dropbox isn't being received correctly.

I checked the same with the Guardian Project NextCloud and uploads behaved as expected.

**Comment by tladesignz** [comment] 2020-04-22 15:44
Hey! Thanks for reporting this.

Unfortunately, I was completely unable to reproduce, even when closing the app and waiting until iOS kills it, then restarting it. It actually went quiet smoothly. :-/

I'm not sure at what state I did the TestFlight. I fixed some behavior about finish recognition in a later commit. Maybe I did your build before that?
I just uploaded a new build (51), which contains the very latest commit and will be available to you soon. Can you re-test with that?

If it still happens, please document, every step I need to take to the minute, like app closing and anything else.

Thank you!

**Comment by tladesignz** [comment] 2020-04-22 15:44
Related: #176

**Comment by roseregina** [comment] 2020-04-24 17:38
Version 2.6.0 (51) (via Testflight) 
Dropbox server (personal account) 
iPhone 11

Behaviour identical to initial issue

This and a couple other things are raising some questions for me about Testflight/ iOs testing and how some of this works. I'm happy to add screen shots, a longer description, or even video if that might be helpful.

**Comment by foundscapes** [comment] 2020-04-24 20:36
Version 2.6.0 (51) (via Testflight)
Dropbox server (personal account)
iPhone xs

I am having the same exact problem.


1.  Add 2 images and 1 video to upload
2. Click on the circled number in the upper right to see queue
3. First file is uploading to Dropbox
4. First file appears as though all of the data has been uploaded, but file is not displayed as complete, upload of next file is not starting even through both image and json are on dropbox (see note below)
5. Pause upload by clicking "Edit" in the upper right
6. Unpause upload by clicking "Done" in the upper right
7. Upload progress wheel displays action again briefly, then file registers as fully uploaded and disappears from the queue
8. At this point, either there are no more images in the queue, or it stalls again like in step 4 and I have to repeat steps 5 & 6 for each image

**Comment by tladesignz** [comment] 2020-04-27 09:22
Okok, don't worry, I believe you.

*However*, it works for me. I can't reproduce it, not even sporadically. As long as that's the case, I can't fix it.

Indeed, a video would be very helpful, so I can find out, what I need to do to reproduce the problem.

Please start with a clean install. Record everything from after installation until the problem arises.

Thanks!

**Comment by foundscapes** [comment] 2020-05-06 20:10
Version 2.6.0 (51) (via Testflight)
Dropbox server (personal account)
iPhone xs

Neither @roseregina nor I could reproduce this problem again, so am closing this ticket

**Closed by foundscapes** 2020-05-06 20:10 UTC
Labels: bug
